name: Test DB build scripts
on: pull_request

jobs:
  build-mimic-iv-psql:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install psql command
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Download demo data from GCP
        run: |
          echo "Downloading MIMIC-IV demo from GCP."
          gsutil -q -u $PROJECT_ID -m cp -r gs://mimic-iv-archive/v2.0/demo ./
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Load icu/hosp data into PostgreSQL
        run: |
          echo "Loading data into psql."
          psql -q -h $POSTGRES_HOST -U postgres -f ${BUILDCODE_PATH}/create.sql
          psql -q -h $POSTGRES_HOST -U postgres -v mimic_data_dir=demo -f ${BUILDCODE_PATH}/load_gz.sql
          echo "Validating build."
          psql -h $POSTGRES_HOST -U postgres -f ${BUILDCODE_PATH}/validate_demo.sql > results
          
          # if we find "FAILED", then we did not pass the build
          if grep -F -q "FAILED" results; then
            echo "Failed the following row counts:"
            head -n 1 results
            grep "FAILED" results
            exit 1
          else
            echo "Built and loaded demo data successfully."
            cat results
          fi

        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          PGPASSWORD: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          BUILDCODE_PATH: mimic-iv/buildmimic/postgres

      - name: Load ed data into PostgreSQL
        run: |
          echo "Loading data into psql."
          psql -q -h $POSTGRES_HOST -U postgres -f ${BUILDCODE_PATH}/create.sql
          psql -q -h $POSTGRES_HOST -U postgres -v mimic_data_dir=demo/ed -f ${BUILDCODE_PATH}/load_gz.sql
          echo "Validating build."
          psql -h $POSTGRES_HOST -U postgres -f ${BUILDCODE_PATH}/validate_demo.sql > results
          
          # if we find "FAILED", then we did not pass the build
          if grep -F -q "FAILED" results; then
            echo "Failed the following row counts:"
            head -n 1 results
            grep "FAILED" results
            exit 1
          else
            echo "Built and loaded demo data successfully."
            cat results
          fi

        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          PGPASSWORD: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          BUILDCODE_PATH: mimic-iv-ed/buildmimic/postgres

  build-mimic-iv-mysql:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Download data from GCP
        run: |
          echo "Downloading MIMIC-IV demo from GCP."
          gsutil -q -u $PROJECT_ID -m cp -r gs://mimic-iv-archive/v2.0/demo ./
          mv demo/hosp/*.csv.gz ./
          mv demo/icu/*.csv.gz ./
          mv demo/ed/*.csv.gz ./
          gzip -d *.csv.gz
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Start MySQL service
        run: |
          sudo /etc/init.d/mysql start
          mysql -u root -proot -e "SET GLOBAL local_infile=1;"
          mysql -u root -proot -e "SET GLOBAL sql_notes=0;"
          mysql -u root -proot -e "create database mimic"

      - name: Load icu/hosp demo data
        run: |
          echo "Loading data into mysql."
          mysql -u root -proot --local-infile=1 mimic < mimic-iv/buildmimic/mysql/load.sql
          mysql -u root -proot mimic < mimic-iv/buildmimic/mysql/validate_demo.sql > results
          
          # if we find "FAILED", then we did not pass the build
          if grep -F -q "FAILED" results; then
            echo "Failed the following row counts:"
            head -n 1 results
            grep "FAILED" results
            exit 1
          else
            echo "Built and loaded demo data successfully."
            cat results
          fi

      - name: Load ed demo data
        run: |
          echo "Loading data into mysql."
          mysql -u root -proot --local-infile=1 mimic < mimic-iv-ed/buildmimic/mysql/load.sql
          mysql -u root -proot mimic < mimic-iv-ed/buildmimic/mysql/validate_demo.sql > results
          
          # if we find "FAILED", then we did not pass the build
          if grep -F -q "FAILED" results; then
            echo "Failed the following row counts:"
            head -n 1 results
            grep "FAILED" results
            exit 1
          else
            echo "Built and loaded demo data successfully."
            cat results
          fi
